CREATE TABLE Winners(
YEAR INTEGER,
SUBJECT TEXT,
WINNER TEXT,
COUNTRY TEXT,
CATEGORY TEXT
);

-- Insert sample data into the Winners table

INSERT INTO Winners
    (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY)
VALUES

    (1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST'),

    (1970, 'PHYSICS', 'LOUIS NEEL', 'FRANCE', 'SCIENTIST'),

    (1971, 'PHYSICS', 'PAUL NELSON', 'FRANCE', 'SCIENTIST'),

    (1971, 'CHEMISTRY', 'HAMILTON SMITH', 'SWEDEN', 'LINGUIST'),

    (1972, 'LITERATURE', 'BERNARD KELSON', 'GERMANY', 'ECONOMIST'),

    (1972, 'ECONOMICS', 'JOSEPH STIGLITZ', 'RUSSIA', 'ECONOMIST'),

    (1973, 'BIOLOGY', 'PHILIPS HOPKINS', 'USA', 'PRIME MINISTER'),

    (1980, 'BIOLOGY', 'RONALD REGAN', 'USA', 'PRESIDENT'),

    (1981, 'PHYSIOLOGY', 'HANNAH ARENDT', 'HUNGARY', 'SCIENTIST'),

    (1975, 'PHYSICS', 'PETER HANFORD', 'CHILE', 'SCIENTIST');

SELECT * FROM Winners;

SELECT * FROM Winners WHERE SUBJECT NOT LIKE 'P%';


